export enum AnalyticsEventType {
  // User Events
  USER_REGISTERED = 'USER_REGISTERED',
  USER_LOGGED_IN = 'USER_LOGGED_IN',
  USER_LOGGED_OUT = 'USER_LOGGED_OUT',
  USER_PROFILE_UPDATED = 'USER_PROFILE_UPDATED',
  USER_BLOCKED = 'USER_BLOCKED',
  USER_DELETED = 'USER_DELETED',
  // Product Events
  PRODUCT_CREATED = 'PRODUCT_CREATED',
  PRODUCT_UPDATED = 'PRODUCT_UPDATED',
  PRODUCT_DELETED = 'PRODUCT_DELETED',
  PRODUCT_VIEWED = 'PRODUCT_VIEWED',
  PRODUCT_FAVORITED = 'PRODUCT_FAVORITED',
  PRODUCT_RESERVED = 'PRODUCT_RESERVED',
  PRODUCT_SOLD = 'PRODUCT_SOLD',
  PRODUCT_REPORTED = 'PRODUCT_REPORTED',
  // Chat Events
  CHAT_CREATED = 'CHAT_CREATED',
  MESSAGE_SENT = 'MESSAGE_SENT',
  USER_BLOCKED_CHAT = 'USER_BLOCKED_CHAT',
  CHAT_REPORTED = 'CHAT_REPORTED',
  // Engagement Events
  FAVORITE_ADDED = 'FAVORITE_ADDED',
  FAVORITE_REMOVED = 'FAVORITE_REMOVED',
  SEARCH_PERFORMED = 'SEARCH_PERFORMED',
  FILTER_APPLIED = 'FILTER_APPLIED',
  // Trust & Safety Events
  USER_REPORTED = 'USER_REPORTED',
  REPORT_RESOLVED = 'REPORT_RESOLVED',
  USER_BANNED = 'USER_BANNED',
  PRODUCT_REMOVED_BY_ADMIN = 'PRODUCT_REMOVED_BY_ADMIN',
  // System Events
  LOGIN_FAILED = 'LOGIN_FAILED',
  RATE_LIMIT_TRIGGERED = 'RATE_LIMIT_TRIGGERED',
  FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',
  UNAUTHORIZED_ACTION_ATTEMPT = 'UNAUTHORIZED_ACTION_ATTEMPT',
}

export enum AnalyticsEntityType {
  PRODUCT = 'PRODUCT',
  USER = 'USER',
  CHAT = 'CHAT',
  RESERVATION = 'RESERVATION',
}

export interface IAnalyticsEvent {
  eventType: AnalyticsEventType;
  userId?: string;
  entityType?: AnalyticsEntityType;
  entityId?: string;
  metadata?: Record<string, unknown>;
  ip?: string;
  userAgent?: string;
}
